#import <Foundation/Foundation.h>
#import "VMGLFoundation.h"

/// Project version number for Mapbox.
FOUNDATION_EXPORT MGL_EXPORT double MapboxVersionNumber;

/// Project version string for Mapbox.
FOUNDATION_EXPORT MGL_EXPORT const unsigned char MapboxVersionString[];

#import "VMGLSettings.h"
#import "VMGLAnnotation.h"
#import "VMGLAnnotationImage.h"
#import "VMGLAnnotationView.h"
#import "VMGLAttributedExpression.h"
#import "VMGLAttributionInfo.h"
#import "VMGLBackgroundStyleLayer.h"
#import "VMGLCalloutView.h"
#import "VMGLCircleStyleLayer.h"
#import "VMGLClockDirectionFormatter.h"
#import "VMGLCluster.h"
#import "VMGLCompassButton.h"
#import "VMGLCompassDirectionFormatter.h"
#import "VMGLComputedShapeSource.h"
#import "VMGLCoordinateFormatter.h"
#import "VMGLDistanceFormatter.h"
#import "VMGLFeature.h"
#import "VMGLFillExtrusionStyleLayer.h"
#import "VMGLFillStyleLayer.h"
#import "VMGLForegroundStyleLayer.h"
#import "VMGLGeometry.h"
#import "VMGLHeatmapStyleLayer.h"
#import "VMGLHillshadeStyleLayer.h"
#import "VMGLImageSource.h"
#import "VMGLLight.h"
#import "VMGLLineStyleLayer.h"
#import "VMGLLocationManager.h"
#import "VMGLLoggingConfiguration.h"
#import "VMGLMapCamera.h"
#import "VMGLMapProjection.h"
#import "VMGLMapSnapshotter.h"
#import "VMGLMapView.h"
#import "VMGLMapViewDelegate.h"
#import "VMGLMapView+IBAdditions.h"
#import "VMGLMultiPoint.h"
#import "VMGLNetworkConfiguration.h"
#import "VMGLOfflinePack.h"
#import "VMGLOfflineRegion.h"
#import "VMGLOfflineStorage.h"
#import "VMGLOpenGLStyleLayer.h"
#import "VMGLOverlay.h"
#import "VMGLPointAnnotation.h"
#import "VMGLPointCollection.h"
#import "VMGLPolygon.h"
#import "VMGLPolyline.h"
#import "VMGLRasterDEMSource.h"
#import "VMGLRasterStyleLayer.h"
#import "VMGLRasterTileSource.h"
#import "VMGLShape.h"
#import "VMGLShapeCollection.h"
#import "VMGLShapeOfflineRegion.h"
#import "VMGLShapeSource.h"
#import "VMGLSource.h"
#import "VMGLStyle.h"
#import "VMGLStyleLayer.h"
#import "VMGLStyleValue.h"
#import "VMGLSymbolStyleLayer.h"
#import "VMGLTilePyramidOfflineRegion .h"
#import "VMGLTileSource.h"
#import "VMGLTypes.h"
#import "VMGLUserLocation.h"
#import "VMGLUserLocationAnnotationView.h"
#import "VMGLVectorStyleLayer.h"
#import "VMGLVectorTileSource.h"
#import "NSExpression+MGLAdditions.h"
#import "NSPredicate+MGLAdditions.h"
#import "NSValue+MGLAdditions.h"
#import "VMGLUserLocationAnnotationViewStyle.h"
